[package]
name = "wicrs_api"
version = "0.3.0"
authors = ["willemml <willem@leit.so>"]
edition = "2018"
license = "GPL-3.0"
description = "Client API for wirc_server."
repository = "https://github.com/wicrs/api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wicrs_server = "0.6"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["macros"] }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
