[package]
name = "wicrs_api"
version = "0.1.0"
authors = ["willemml <willem@leit.so>"]
edition = "2018"
license = "GPL-3.0"
description = "Client API for wirc_server."
repository = "https://github.com/wicrs/api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wicrs_common = "0.1"
reqwest = { version = "0.10", features = ["json"] }
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
tokio-test = "0.3"
